mediagoblin:
  build: .
  links:
    - db:db
  ports:
    - "6543:6543"
    - "8888:8888"
  volumes:
    - ./media:/var/media
  environment:
    - UPLOADDIR=/var/media
    - DATABASE=/var/media/files.db
db:
  image: postgres
  volumes:
    - /var/lib/postgresql/data
